name: Create preview environment

on:
  pull_request:
    branches: [main, milkomeda-c1-testnet]
  push:
    branches: [main, milkomeda-c1-testnet]

concurrency:
  # The preview script can't handle concurrent deploys
  group: codepreview
  cancel-in-progress: false

# TODO: Define minimal permissions, I haven't found which one is necessary to allow writing comments on commits
# see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
#permissions:
#  contents: read # for checkout

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Install ansible
        run: python3 -m pip install --user ansible

      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prepare build (pr)
        if: ${{ (github.head_ref || github.ref_name) != 'main' }}
        run: npm run build:milkomeda-c1-testnet

      - name: Prepare build (main)
        if: ${{ (github.head_ref || github.ref_name) == 'main' }}
        run: npm run build:milkomeda-c1

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$CODEPREVIEW_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking=no" > ~/.ssh/config
        shell: bash
        env:
          CODEPREVIEW_PRIVATE_KEY: ${{secrets.CODEPREVIEW_PRIVATE_KEY}}

      - name: Create codepreview scripts
        run: |
          rm -rf ./infra
          curl -u "github:$CODEPREVIEW_TOKEN" -O https://djed.codepreview.io/djed.zip
          unzip djed.zip -d .
          chmod +x ./infra/scripts/*.sh
        shell: bash
        env:
          CODEPREVIEW_TOKEN: ${{secrets.CODEPREVIEW_TOKEN}}

      - name: Create preview env
        run: cd infra && ./scripts/deploy-preview.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.number }}
